[package]
name = "jemallocator"
version = "0.1.7"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["allocator"]
repository = "https://github.com/alexcrichton/jemallocator"
homepage = "https://github.com/alexcrichton/jemallocator"
documentation = "https://docs.rs/jemallocator"
description = """
A Rust allocator backed by jemalloc
"""

[lib]
test = false
bench = false

[workspace]
members = ["systest"]

[dependencies]
jemalloc-sys = { path = "jemalloc-sys", version = "0.1.5" }
libc = "0.2.8"

[features]
profiling = ["jemalloc-sys/profiling"]
debug = ["jemalloc-sys/debug"]
